### ISSUE TITLE
P2P Websocket Error

### ISSUE THREAD

**Issue by SeptBlast** [15Dkatz/sf-chain-guides#5]
I am using windows 10 as the host machine

PS D:\blockchain\source_code\in-block> npm run dev HTTP_PORT=3002 P2P_PORT=5002 PEERS=ws://localhost:5001

> in-block@1.0.0 dev D:\blockchain\source_code\in-block
> nodemon ./app "HTTP_PORT=3002" "P2P_PORT=5002" "PEERS=ws://localhost:5001"

[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node ./app HTTP_PORT=3002 P2P_PORT=5002 PEERS=ws://localhost:5001`
Listening for peer-to-peer connections on: 5001
events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: listen EADDRINUSE :::3001
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Function.listen (D:\blockchain\source_code\in-block\node_modules\express\lib\application.js:618:24)
    at Object.<anonymous> (D:\blockchain\source_code\in-block\app\index.js:26:5)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
[nodemon] app crashed - waiting for file changes before starting.

**Comment by dirtydeM0n** [comment]
I'm also stuck at this. Can't seem to figure it out.

**Comment by sarangsurve** [comment]
Use cygwin or any unix-terminal
Because window's cmd handles websocket only one at a time
So my suggestion is to use linux or unix terminal and recommending mostly to use OS X with iTerm2 application if going through @15Dkatz Udemy's Tutorial
This is screenshot where I was able to run websocket on Cygwin using Windows 8.1
![1](https://user-images.githubusercontent.com/34687590/50659528-ee718580-0fc2-11e9-85f8-0fa9e61f0f8e.png)

**Comment by SeptBlast** [comment]
thanks @sarangsurve 
its also working if you had github bash mode installed in windows. No need to install Cygwin separately. Basic bash scripts can be easily used from there.
